# Usage:   brew bundle

# Config
cask_args appdir: '~/Applications'

# Taps
tap 'homebrew/cask'

# Packages
brew 'git'
brew 'coreutils'
brew 'moreutils'
brew 'findutils'
brew 'gnu-sed'
brew 'gawk'
brew 'grep'
brew 'bash'
brew 'zsh'
brew 'htop'
brew 'p7zip'
brew 'ssh-copy-id'
brew 'unison'
brew 'pv'
brew 'ag'
brew 'ansible'
brew 'packer'
brew 'terraform@0.13'
brew 'tmux'
brew 'awscli'
brew 'geckodriver'
brew 'mysql@5.6'
brew 'postgresql@11'
brew 'sqlite'
brew 'the_silver_searcher'
brew 'act'
brew 'docker-clean'

# Casks
cask 'firefox'
cask 'iterm2'
cask 'atom'
cask 'cyberduck'
cask 'macdown'
cask 'mysqlworkbench'
cask 'postman'
cask 'skim'
cask 'sequel-pro'
cask 'visual-studio-code'
cask 'eclipse-java'
cask 'virtualbox'
cask 'virtualbox-extension-pack'
cask 'vagrant'
cask 'tunnelblick'
cask 'psequel'
cask 'amazon-workspaces'

# completion
brew 'bash-completion@2'
brew 'packer-completion'
brew 'vagrant-completion'
brew 'docker-completion'
brew 'docker-compose-completion'
brew 'brew-cask-completion'
brew 'maven-completion'
brew 'tmuxinator-completion'
brew 'zsh-completions'
